defmodule TalesForgeWeb.Endpoint do
  @moduledoc """
  Phoenix endpoint: static files, the signed session cookie, the LiveView socket and the router.
  """

  use Phoenix.Endpoint, otp_app: :ex_tales_forge

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it (note: changing
  # the cookie format logs everyone out once).
  #
  # max_age makes it a persistent cookie, so a GitHub sign-in lasts up to 30
  # days (team membership is still rechecked on every request); without it browsers (notably Safari) drop it as a
  # browser-session cookie. secure is compile-time (true in config/prod.exs)
  # because these options are also baked into the LiveView socket's
  # connect_info, and local dev runs over plain http.
  @session_options [
    store: :cookie,
    key: "_ex_tales_forge_key",
    signing_salt: "0TBCbxzZ",
    same_site: "Lax",
    max_age: 60 * 60 * 24 * 30,
    secure: Application.compile_env(:ex_tales_forge, :secure_session_cookie, false)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :ex_tales_forge,
    gzip: not code_reloading?,
    only: TalesForgeWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :ex_tales_forge
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug TalesForgeWeb.Router
end
